server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true


      routes:
        # Auth Service
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**,/api/users/**

        # Startup Service
        - id: startup-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/startups/**,/api/milestones/**,/api/team/**

        # Pitch Service
        - id: pitch-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/pitchs/**,/api/ai/**

        # Investor Service
        - id: investor-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/investors/**,/api/matching/**,/api/connections/**

        # Analytics Service (optional)
        - id: analytics-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/dashboard/**,/api/analytics/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG